_id: "453983995701493760"
name: Mockplexity
description: null
model: ""
createdAt: 2024-06-06T18:10:19.190Z
updatedAt: 2024-06-06T19:47:43.989Z
createdBy: z1mTPnKArR2kRj2VTLH91zPDi9F9vJ1sazX
updatedBy: z1mTPnKArR2kRj2VTLH91zPDi9F9vJ1sazX
pinnedAt: null
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: null
